/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Counter: (() => {
      const tableId = new TableId("", "Counter");
      return defineComponent(
        world,
        {
          value: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Map: (() => {
      const tableId = new TableId("", "Map");
      return defineComponent(
        world,
        {
          uniqueId: RecsType.BigInt,
          startAt: RecsType.BigInt,
          playersIn: RecsType.Number,
          dimension: RecsType.Number,
          locationsInitialized: RecsType.Boolean,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    MapLocations: (() => {
      const tableId = new TableId("", "MapLocations");
      return defineComponent(
        world,
        {
          kind: RecsType.Number,
          owner: RecsType.String,
          color: RecsType.Number,
          x_: RecsType.Number,
          y_: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Player: (() => {
      const tableId = new TableId("", "Player");
      return defineComponent(
        world,
        {
          position: RecsType.Number,
          x: RecsType.Number,
          y: RecsType.Number,
          coinR: RecsType.Number,
          coinG: RecsType.Number,
          coinB: RecsType.Number,
          coinSTABLE: RecsType.Number,
          stamina: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
