// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum Structures {
  None,
  Mine,
  Exchange
}

enum Colors {
  None,
  Red,
  Green,
  Blue
}
